### ISSUE TITLE
7TV emotes not working on streamlabs?

### ISSUE THREAD

**Issue by AlfaeLive** [liquidnya/pronouns-chat#1]
I just added some 7TV emotes to my twitch but they don't show up in the chat. I made a new chat box without this custom chat and it worked just fine in that one.

**Comment by liquidnya** [comment]
> I just added some 7TV emotes to my twitch but they don't show up in the chat. I made a new chat box without this custom chat and it worked just fine in that one.

Are you using Streamlabs or StreamElements?
Which emote did you add to your chat?

7TV emotes are handled by Streamlabs and StreamElements, and not by the custom chat.
However the custom chat can be set up to hide frog emotes, but the default is not to hide those emotes – also it is only a fixed list of global 7TV emotes that would be hidden if the setting was turned on (which again it's not like this by default).
There is also a way to specify emote overrides, but that requires changing the JS source code.

**Comment by liquidnya** [comment]
If you were using StreamElements:
Do other custom chats work with that 7TV emote?
Like for example the [Minimal Chat by MrBoost](https://blog.streamelements.com/top-10-custom-widgets-on-streamelements-826e8fdaf76b#2d88) or [DynamicChatBubbles](https://github.com/zaytri/stream-elements-widgets/tree/main/DynamicChatBubbles).

**Comment by AlfaeLive** [comment]
Not sure what happened but it randomly started working, sorry for taking up your time 👍
